services:
  - type: web
    name: monitor-de-precos-5800x3d
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /tmp/price-monitor-data
